### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Orange-wjc** [luigifreda/3dmr#5]
when I test multi-robot exploration through PyQt GUIs (i.e., ./main.py and ./main_pioneer.py and ./main_jackal.py), it seems that there are some errors for UGVs in rviz, and it can not run correctly (shown in the figure).I have deleted the temp file and re-executed ./install-vrep.sh, but it still hasn't been resolved.

<img width="1449" height="989" alt="Image" src="https://github.com/user-attachments/assets/a72e061d-0a21-4f1c-ab3c-e5925c0a9a0a" />

<img width="1376" height="903" alt="Image" src="https://github.com/user-attachments/assets/40b996be-863e-472b-ab42-79e136ae73a6" />

**Comment by luigifreda** [comment]
Hi,  
Thanks for your feedback!  

- Could you let me know which installation procedure you followed and share the console log you obtained?  
- Also, could you share the console output you get when running one of the following:  
  - `./main.py`  
  - `./main_pioneer.py`  
  - `./main_jackal.py`

**Comment by Orange-wjc** [comment]
Thank you for your response! I have removed any "temp" folder, and have tried to launch ./install-vrep.sh again.
<img width="1210" height="564" alt="Image" src="https://github.com/user-attachments/assets/a0a22b3d-c7d1-440d-8ca0-c6810fa1a99a" />
The following is the console output log when I execute ./main.py.

<img width="2560" height="1600" alt="Image" src="https://github.com/user-attachments/assets/e8bcf07a-b23c-4ba3-8528-1fbabb68e618" />

<img width="2560" height="1600" alt="Image" src="https://github.com/user-attachments/assets/e9520fee-cd47-4029-a127-ab82980b73df" />

**Comment by luigifreda** [comment]
Thanks for sharing the details. I’ll need a bit more information to better support you.

Yesterday, I pushed a few updates and verified that everything works correctly under Docker. I tested the system using [rosdocker](https://github.com/luigifreda/rosdocker) with the `noetic_cuda` container.
Please, git pull the new updates.

Could you please check the following:

## 1) System setup
Please confirm that you are running **Ubuntu 20.04** with **ROS Noetic**, as required [here](https://github.com/luigifreda/3dmr?tab=readme-ov-file#prerequisites).

## 2) Installation log
Run:
```bash
./install.sh
```
and share the full log.

## 4) Build log
Run:
```bash
./clean_all.sh
./build_all.sh
```
and share the full log as well.

## 4) Testing VREP

Also, please confirm that the test described [here](https://github.com/luigifreda/3dmr/blob/main/INSTALL.md#test-v-rep-installation) runs successfully on your system.

**Comment by Orange-wjc** [comment]
Thank you very much for your answers. I reinstalled this project according to your steps and finally got it running successfully. However, there are still some issues. When I run ./main_pioneer.py and ./main_jackal.py, the camera doesn't work properly.
when I run ./main_pioneer.py.
<img width="2373" height="1460" alt="Image" src="https://github.com/user-attachments/assets/c82c44ba-48ea-47b6-b401-37ed148a1bdd" />

<img width="2359" height="1472" alt="Image" src="https://github.com/user-attachments/assets/cca9fc20-11f3-4219-9705-01a562e074af" />
when I run ./main_jackal.py
<img width="2358" height="1457" alt="Image" src="https://github.com/user-attachments/assets/e23b9ff8-b101-43f7-8b5e-608bf784b034" />
Additionally, when I run the navigation module of ./main_jackal.py, the UGV and the map fail to load properly.
<img width="2460" height="1540" alt="Image" src="https://github.com/user-attachments/assets/6c3d5dca-4355-43d0-86a1-9140dea782a8" />

**Comment by luigifreda** [comment]
Hi all,
I’ve pushed a few fixes and improvements. Please pull the latest changes and follow these steps:
1. Remove any VREP_ROOT_DIR settings from your ~/.bashrc.
2. Clean, reinstall, and rebuild everything:
  ```bash
  ./clean_all.sh
  ./install.sh
  source source_all.bash
  ./build_all.sh
  ```

I also addressed some potential locale-related issues, which should now be resolved.
Regarding the Jackal test: on the first launch, Gazebo may take a bit of time before the robot’s camera and sensors become visible. Once it “warms up,” everything runs smoothly on subsequent runs.
LMK

**Comment by Orange-wjc** [comment]
Hello, I followed your steps and executed them. Unfortunately, some more serious errors have occurred. None of the modules can display the robot vehicle anymore. It seems this is because I removed any VREP_ROOT_DIR settings from my ~/.bashrc.
It seems that after I removed the VREP_ROOT_DIR settings from ~/.bashrc, the script might have failed to obtain this path, which resulted in the missing target path for the copy command.
<img width="1211" height="581" alt="Image" src="https://github.com/user-attachments/assets/17a56c15-116e-4da8-8413-b42edc7bb503" />
When I run ./main.py
<img width="2353" height="1549" alt="Image" src="https://github.com/user-attachments/assets/7db025f7-dff6-4ae9-bdbd-916fdb8db298" />

**Comment by luigifreda** [comment]
Hi,
It looks like there’s a potential issue with non-interactive mode when running things inside Docker containers. This prevents .bashrc from being sourced correctly, which means the added VREP settings may not be applied.

To fix this (or in any case), please pull the latest changes and then run:
```bash
./install-vrep.sh
./build_all.sh
```

Also, please note that on the first launch, Gazebo may take some time to warm up the Jackal simulation.

Let me know how it goes.

**Comment by Orange-wjc** [comment]
Thank you for your reply. I pulled the latest code and followed your steps, and the robot was displayed successfully. However, there are still two issues.
The cameras in ./main_jackal.py and ./main_pioneer.py still cannot display images properly. I waited for a while as you mentioned, but the cameras still failed to show images after that. I'm wondering if it's a problem with my operation. But when I run roslaunch interface_nbvp_rotors multiagent_flat_exploration.launch, the camera of the UAV can display images normally.
<img width="2266" height="1205" alt="Image" src="https://github.com/user-attachments/assets/2c6b10f3-bb99-4526-8777-6b1100defefe" />
<img width="2364" height="1215" alt="Image" src="https://github.com/user-attachments/assets/8c0c6eed-bcbb-4850-a724-0fb6650ff34f" />
<img width="2501" height="1218" alt="Image" src="https://github.com/user-attachments/assets/7037a2ce-a14c-4fb9-99c0-5f5af5883152" />
Another issue is that the navigation module of ./main_jackal.py still cannot display the robot. It still didn't show up properly even after I waited for a while.

<img width="2417" height="1218" alt="Image" src="https://github.com/user-attachments/assets/4363233e-dec1-4cff-8507-a863c9ae266f" />

**Comment by luigifreda** [comment]
Hi,
Thanks for your feedback.
Could you please confirm whether you are running Ubuntu 20.04 with ROS Noetic, as required [here](https://github.com/luigifreda/3dmr?tab=readme-ov-file#prerequisites).
Could you share the following details so I can better understand your setup:
- Operating system and version
- CPU and GPU
- If using Docker, which container are you running

I asked for this information earlier, but I haven’t received a response yet. It would really help with troubleshooting.

In the meantime, could you also try installing and testing 3dmr under Docker using [rosdocker](https://github.com/luigifreda/rosdocker)
 with the `noetic_cuda` container? I haven’t encountered any issues in that environment.

**Comment by luigifreda** [comment]
Following up on my previous message, I wasn’t able to reproduce the issue on my side.

I tested the system in several environments:
- Native Ubuntu 20.04 with Noetic
- rosdocker `noetic_cuda` on Ubuntu 20.04
- rosdocker `noetic` on Ubuntu 20.04
- rosdocker `noetic_cuda` on Ubuntu 24.04 (with and without NVIDIA runtime)
- rosdocker `noetic` on Ubuntu 24.04 (with and without NVIDIA runtime)

In all of these setups, everything runs smoothly, and the RViz cameras are always visible.

For the Jackal navigation issue, could you try switching Gazebo from headless to normal mode? That way, you can confirm if Gazebo is actually running and also see how long it takes to load. Hopefully, this will give us a clearer idea of what’s going on.

<img width="434" height="577" alt="Image" src="https://github.com/user-attachments/assets/dd0b273c-63fe-4aff-9620-09b846e7727a" />

**Comment by Orange-wjc** [comment]
Hello, thank you for your reply. I'm using Ubuntu 20.04 with Noetic. I'm currently installing rosdocker and plan to try running things on rosdocker as you suggested.Regarding the CPU and GPU models of my device: I'm using the Lenovo Legion Y9000P 2024 base model. It is equipped with an Intel Core i9-14900HX processor and an NVIDIA GeForce RTX 4060 graphics card.
When I select "Launch exploration", Gazebo can open normally. 
<img width="2536" height="1273" alt="Image" src="https://github.com/user-attachments/assets/cac0cc2b-d8c7-4cb4-b8cb-d2840c7de51c" />
However when I choose "Launch navigation", Gazebo fails to open properly, and the robot does not display correctly in RViz. 
<img width="2531" height="1341" alt="Image" src="https://github.com/user-attachments/assets/b1e80eae-65fa-4735-92bb-2edcdb129427" />
Similarly, when I select "Launch Gazebo", Gazebo cannot open properly, and the robot is not displayed correctly in RViz either.
<img width="2513" height="1344" alt="Image" src="https://github.com/user-attachments/assets/ccdb9f9e-e4c6-476a-b8e9-a38c7c6e4f81" />

**Comment by luigifreda** [comment]
Could you let me know which versions of CUDA and the NVIDIA drivers you’re using? Also, how did you check that your NVIDIA graphics setup is working correctly? I suspect the issue might be related to graphics conflicts, but in that case I’m not sure how best I can support you further.

From what I can see, your problems seem related to Gazebo and camera images, but I haven’t been able to reproduce them on my side (different laptops, different OSs, different docker containers).

It would be very helpful if you could share more details about the error messages. The screenshot you provided is in a language I don’t understand, so any additional explanation would help me follow what’s happening.

Have you already tried any troubleshooting steps on your side?

As another test, I’d recommend cloning the repository from scratch into a new, clean folder and running the installation process again.

**Comment by Orange-wjc** [comment]
Hello, thank you for your patient replies! I have resolved all the issues. The camera was unable to display images properly because I was missing the image_transport_plugins dependency package—after installing this package, the camera started working correctly.

Regarding the problem where the robot couldn't be displayed properly in the navigation module of the Jackal package, I suspect it was due to my outdated CUDA version. My NVIDIA driver version is 560.35.03, and my original CUDA version was 10.1. After updating the CUDA version to 12.6, all issues were resolved.

Thank you very much for your help!

<img width="2525" height="1337" alt="Image" src="https://github.com/user-attachments/assets/1a20fac8-1440-4f72-9430-d931445a31a9" />

<img width="2492" height="1227" alt="Image" src="https://github.com/user-attachments/assets/e8ba30e4-243d-4bdc-b1ae-b0ba807e6898" />

**Comment by Orange-wjc** [comment]
Hello, most of the issues in this project have been resolved. However, when I run ./main.py and select the normal mode, the problem that the robot is not displayed in RViz still occurs.
normal model
<img width="2519" height="1239" alt="Image" src="https://github.com/user-attachments/assets/f49ba919-e8a4-4710-9804-37d5a0e866c5" />

<img width="2538" height="1288" alt="Image" src="https://github.com/user-attachments/assets/ebb3bc81-c632-490e-83c3-940b414e60aa" />

<img width="2528" height="1239" alt="Image" src="https://github.com/user-attachments/assets/1500dc37-de9c-4c32-9fd7-c8d41b7bee17" />
normal autostart model
<img width="2521" height="1245" alt="Image" src="https://github.com/user-attachments/assets/0800d0f0-fde5-4085-a981-598e2d88b161" />

**Comment by luigifreda** [comment]
Hi,
Glad to hear you solved the issues. 

As a general piece of advice, I recommend keeping your GPU drivers fully updated and functional. It often prevents many unexpected problems.

> The camera was unable to display images properly because I was missing the image_transport_plugins dependency package—after installing this package, the camera started working correctly.

That’s a bit weird. The ROS `image_transport_plugins` package should already be installed automatically by the [install.sh](https://github.com/luigifreda/3dmr/blob/main/install.sh#L153)
 script. Did you update and re-run that script?

> However, when I run ./main.py and select the normal mode, the problem that the robot is not displayed in RViz still occurs. > normal model

As explained in the [navigation README](https://github.com/luigifreda/3dmr/blob/main/README.navigation.md#v-rep-modes), in V-REP `normal` mode you need to manually **press the play button** (the simulation does not start automatically in this mode). From your screenshot, I can see that the play button wasn’t pressed:

<img width="1548" height="1221" alt="Image" src="https://github.com/user-attachments/assets/aafbc442-db37-455c-8a3c-bdd22949fe0b" />

<br><br>
Thanks again for your feedback.
Please close this issue if everything is working now.

All the best

**Comment by Orange-wjc** [comment]
Hello,

Thank you so much for your patient replies—all the issues have been successfully resolved! I still don't quite understand what caused the failure in installing the image_transport_plugins package. I'm certain that I updated and re-ran that script, and I also tried downloading the project again in new files many times.

Finally, thank you sincerely!
